name: ledgerdot
description: Business management & Invoicing
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #stacked framework
  stacked: ^3.2.0
  stacked_services: ^1.0.0
  stacked_themes: ^0.3.10
  stacked_hooks:
  flutter_hooks:

  auto_route: ^7.8.3

  #fab speed buttons
  flutter_speed_dial:

  printing: ^5.11.0
  #svg
  flutter_svg:
  # create pdf document
  pdf: ^3.1.0

  # save file
  path_provider: ^2.0.1

  # open pdf document
  open_file: ^3.1.0

  # format dates for invoice
  intl: ^0.18.0

  # save files from web
  html: ^0.15.0

  freezed_annotation: #freeze
  buttons_tabbar: ^1.3.7+1

  #ui
  raven:

dev_dependencies:
  flutter_test:
    sdk: flutter

  #mandatory generators
  build_runner: any
  #this generates the app.app.dart and locator.dart
  stacked_generator: ^1.5.1
  freezed:

  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.0

#ASSETS
flutter:
  uses-material-design: true
  assets:
    - assets/logo/ledger_300x150_black_transparent.svg
    - assets/logo/ledger_300x150_revolutWhite_transparent.svg
    - assets/logo/ledger_300x150_white_transparent.svg
    - assets/logo/devbutton.svg
    - assets/placeholder/user.svg

  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
